steps:
  # Build Docker image dari folder backend
  - name: "gcr.io/cloud-builders/docker"
    dir: "backend"  # Jalankan docker build dari folder backend
    args: [
      "build",
      "-t", "gcr.io/$PROJECT_ID/backend-7",
      "."
    ]

  # Push image ke Container Registry / Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend-7"]

  # Deploy image ke Cloud Run dengan nama service: tugas6-backend
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "run",
      "deploy",
      "backend_7",
      "--image", "gcr.io/$PROJECT_ID/backend-7",
      "--timeout", "1000s",
      "--port", "5000",
      "--region", "us-central1",
      "--allow-unauthenticated"
    ]

options:
  logging: CLOUD_LOGGING_ONLY
