GET http://localhost:5000/notes


###
POST http://localhost:5000/notes
Content-Type: application/json

{
  "title": "Catatan Harian",
  "content": "Hari ini saya belajar membuat RESTful API dengan Node.js dan Express.",
  "author": "Anisa"
}



###
PUT http://localhost:5000/notes/6
Content-Type: application/json

{
    "title": "Upadate lalala",
    "content": "daftar belanjaan: garam, sampo, facewash, indomie, tissue, sabun",
    "author": "virda"
}


###
DELETE http://localhost:5000/notes/13
